;; init.el --- Just loading the real thing
;; Fuck the bell sound
(setq ring-bell-function 'ignore)
;; Load up Org Mode and Babel
;; and load the configuration file
(setq dotfiles-dir (file-name-directory (or load-file-name (buffer-file-name))))
(add-to-list 'load-path
	     (expand-file-name "lisp" (expand-file-name "org" (expand-file-name "src" dotfiles-dir))))
(require 'org-install)
(org-babel-load-file (expand-file-name "config.org" dotfiles-dir))

;; ------------------------ Generated By Emacs ----------------------------------
